[package]
name = "ewaf-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
cap-std.workspace = true
serde.workspace = true
unicode-normalization.workspace = true
unicode-general-category.workspace = true

[dev-dependencies]
tempfile.workspace = true

[[bench]]
name = "large_operations"
harness = false
