[workspace]
members = ["crates/ewaf-core", "crates/ewaf-ffi"]
resolver = "2"

[workspace.package]
version = "1.0.3"
edition = "2021"
rust-version = "1.85"
repository = "https://github.com/tlolabs/ewaf"

[workspace.dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["std"] }
cap-std = "3.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-normalization = "0.1"
unicode-general-category = "1.1"
tempfile = "3.23"

[profile.release]
lto = "thin"
codegen-units = 1
